# Generated by Django 4.2.5 on 2023-09-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_url_blog_date_alter_blog_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 21, 56, 33, 525300)),
        ),
    ]
