# Generated by Django 4.2.5 on 2023-09-24 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 24, 19, 3, 14, 884273, tzinfo=datetime.timezone.utc)),
        ),
    ]
